language = "ocaml"
status = "alpha"

[documentation]
description  = """
ocaml driver for [babelfish](https://github.com/bblfsh/bblfshd).
"""

[runtime]
os = "alpine"
go_version = "1.8"
native_version = ["4.04.1-r0"]